# Generated by Django 5.2.4 on 2025-07-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headertitle',
            name='img',
            field=models.ImageField(null=True, upload_to='home'),
        ),
    ]
