# Generated by Django 5.2.4 on 2025-07-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_whatwedo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='home')),
            ],
        ),
    ]
