# Generated by Django 5.2.4 on 2025-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_problems'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheCleantSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('img', models.ImageField(null=True, upload_to='home')),
            ],
            options={
                'verbose_name': 'The Cleant Say',
                'verbose_name_plural': 'The Cleant Says',
            },
        ),
    ]
