# Generated by Django 5.2.4 on 2025-07-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_thecleantsay'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedo',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='home'),
        ),
    ]
