# Generated by Django 5.2.4 on 2025-07-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_whatwedo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('text', models.TextField(verbose_name='text')),
                ('profession', models.CharField(max_length=100, verbose_name='profession')),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='home')),
                ('img2', models.ImageField(null=True, upload_to='', verbose_name='home')),
            ],
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='img',
            field=models.ImageField(default=0, upload_to='', verbose_name='home'),
            preserve_default=False,
        ),
    ]
