# Generated by Django 5.2.4 on 2025-07-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_about_alter_whatwedo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='img',
        ),
        migrations.RemoveField(
            model_name='about',
            name='img2',
        ),
    ]
