# Generated by Django 5.2.4 on 2025-07-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_about_img_remove_about_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
