# Generated by Django 5.2.4 on 2025-07-31 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_about_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='staffs', verbose_name='staffs image')),
                ('description', models.TextField(verbose_name='description')),
                ('aboutt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_r', to='main.about')),
            ],
        ),
    ]
