# Generated by Django 5.2.4 on 2025-07-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_getting'),
    ]

    operations = [
        migrations.AddField(
            model_name='getting',
            name='img',
            field=models.ImageField(default=0, upload_to='home'),
            preserve_default=False,
        ),
    ]
