# Generated by Django 5.2.4 on 2025-07-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_getting_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='price')),
                ('img', models.ImageField(upload_to='ticket', verbose_name='image')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('storage', models.IntegerField(verbose_name='storage')),
                ('status', models.CharField(choices=[('GB', 'GB'), ('TB', 'TB')], default='TB', max_length=2)),
                ('LTS', models.BooleanField(default=True, verbose_name='Life-time Support')),
                ('PAO', models.BooleanField(default=True, verbose_name='Premium Add-Ons')),
                ('FN', models.BooleanField(default=True, verbose_name='Fastest Network')),
                ('MO', models.BooleanField(default=True, verbose_name='More Options')),
            ],
        ),
    ]
